---

- import_playbook: core.yml

- hosts: webservers
  user: XXX

  tasks:
    - name: Crear directorio CCProyecto
      become: yes
      file:
        path: /CCProyecto
        state: directory
        mode: '0755'

    # Download microservice 1 (News) from github
    - name: Descarga de microservicio 1 (News) de Github.
      become: yes
      git: 
        repo: https://github.com/OscarRubioGarcia/CCProyecto.git
        version: master
        dest: /home/XXX/CCProyecto

    - name: Install virtualenv via pip
      pip:
        name: virtualenv
        executable: pip3
      become: yes
      become_user: root

    - name: Instalar requisitos del App.
      become: yes
      pip: 
        requirements: /home/XXX/CCProyecto/requirements.txt
        virtualenv: /home/XXX/CCProyecto/venv

    - name: Copy file to folder
      copy: 
        src: /home/oscar/Desktop/scripts/activateVenvAndDeploy
        dest: /home/XXX/CCProyecto/activateVenvAndDeploy
      become: yes

    - name: Give permissions to file
      file:
        dest: /home/XXX/CCProyecto/activateVenvAndDeploy
        mode: a+x
      become: yes

    - name: Initialize App News
      shell: ./activateVenvAndDeploy
      args:
        chdir: /home/XXX/CCProyecto
      become: yes
