language: python
python:
  - "3.4"      # Earliest branch
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7.5"
  - "3.8-dev"  # dev build
# command to install dependencies and coverage
install:
 - pip install -r requirements.txt
 - pip install coverage
# command to run tests
script:
 - invoke testAllManual
 