FROM alpine:3.10

MAINTAINER Oscar Rubio Garcia 

WORKDIR /code
ENV PORT="DEFAULT"

RUN apk update && apk upgrade && apk add py-pip linux-headers python3 py3-virtualenv python-dev bash

RUN mkdir /var/lib/cassandra
RUN mkdir /var/log/cassandra

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m virtualenv --python=/usr/bin/python3 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements-img.txt requirements.txt
RUN pip install -r requirements.txt
RUN rm -rf requirements.txt

COPY LICENSE tasks.py setup.py /code/
COPY project2 /code/project2

CMD invoke runGunicornAsyncParamsComments -p ${PORT}
